language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4snapshot
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
    - php: 7.4snapshot
install:
  - composer i -n -o --no-suggest --prefer-dist

script:
  - composer test:ci

cache:
  directories:
    - $HOME/.composer/cache
